2025-04-21 02:24:54,092 - root - INFO - Logging initialized. Log file: logs\network_scanner_20250421_022454.log
2025-04-21 02:24:54,092 - main - INFO - Starting Network Scanner & Management Tool
2025-04-21 02:24:54,092 - main - INFO - Application started by user: pc
2025-04-21 02:24:54,094 - main - INFO - Start time: 2025-04-21 01:24:54 UTC
2025-04-21 02:24:54,095 - config.settings - INFO - Settings loaded successfully
2025-04-21 02:24:54,353 - gui.scanner_tab - INFO - Onglet Scanner initialisé
2025-04-21 02:24:54,368 - gui.devices_tab - INFO - Chargement de 23 appareils depuis devices.json
2025-04-21 02:24:54,374 - gui.main_window - INFO - Main window initialized
2025-04-21 02:25:11,123 - gui.scanner_tab - INFO - Scan démarré: 192.168.1.0/24, type=ping, timeout=1s
2025-04-21 02:25:11,124 - gui.scanner_tab - ERROR - Erreur lors du scan ping: 'ScanThread' object has no attribute '_is_host_active'
Traceback (most recent call last):
  File "C:\GAMES\PFS\files\network_scanner_project\gui\scanner_tab.py", line 111, in _scan_ping
    if self._is_host_active(ip):
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ScanThread' object has no attribute '_is_host_active'
2025-04-21 02:25:11,131 - gui.scanner_tab - ERROR - Erreur lors du scan: 'ScanThread' object has no attribute '_is_host_active'
Traceback (most recent call last):
  File "C:\GAMES\PFS\files\network_scanner_project\gui\scanner_tab.py", line 64, in run
    self._scan_ping(self.ip_range)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\GAMES\PFS\files\network_scanner_project\gui\scanner_tab.py", line 111, in _scan_ping
    if self._is_host_active(ip):
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ScanThread' object has no attribute '_is_host_active'
2025-04-21 02:25:11,133 - gui.scanner_tab - INFO - Scan terminé: 0 appareils trouvés
